### ISSUE TITLE
View transaction data leads to 404 page not found

### ISSUE THREAD

**Issue by jiaodong** [AtlasProtocol/ATP#1]
Is this expected ?

Url: https://explorer.nebulas.io/#/404!/tx/3b83ba4280a2d0db408706da8170e3d4865ec6d1af42873897f215453fe12709

**Comment by atlaspio** [comment]
It was caused by mainnet launch resulting explorer being pointing to mainnet while the demo transaction was in testnet.

We will recreate this demo soon hence will not fix this.
